name = "Uni Notes Theme"
license = "MIT"
licenselink = "https://github.com/pinny87/uni-site-theme/blob/master/LICENSE.md"
description = "Hugo Theme for my University Notes site"
homepage = "http://uni.dylanpinn.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Dylan Pinn"
  homepage = "dylanpinn.com"
